const sampleProducts = [
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  },
  {
    image: { url: "", filename: "" },
    name: "",
    description: "",
    price: 100,
    category: "",
  }
];

module.exports = {data : sampleProducts};